# Generated by Django 4.2 on 2023-04-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamreg', '0002_alter_entry_options_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='leader',
            field=models.BooleanField(default=False),
        ),
    ]
